name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
    - name: Log into Quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: test
      run: docker-compose run --rm app sh -c 'python manage.py wait_for_db  && python manage.py test'
    - name: Lint
      run: docker-compose run --rm app sh -c "flake8"
